# Support Vector Machines for MNIST Digit Recognition 
 

In [8]:
# Imports
import numpy as np
from sklearn import svm, metrics

In [9]:
# For loading MNIST data. Code already implemented in the mnist_loader.py file.
import mnist_loader

In [10]:
training_set, validation_set, test_set = mnist_loader.load_data()

training_data = training_set[0]
training_data_labels = training_set[1]

test_data = test_set[0]
test_data_labels = test_set[1]

 The ``training_data`` is returned as a tuple with two entries.
The first entry contains the actual training images.  This is a
numpy ndarray with 50,000 entries.  Each entry is, in turn, a
numpy ndarray with 784 values, representing the 28 * 28 = 784
pixels in a single MNIST image.

The second entry in the ``training_data`` tuple is a numpy ndarray
containing 50,000 entries.  Those entries are just the digit
values (0...9) for the corresponding images contained in the first
entry of the tuple.

The ``validation_data`` and ``test_data`` are similar, except
each contains only 10,000 images.

In [11]:
# Training data. We have 784 (28 * 28) data entries for each training image.
print training_data
print "No. of training images: %s" % len(training_data[0])
print "No. of entries for each image: %s" % len(training_data)

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
No. of training images: 784
No. of entries for each image: 50000


In [12]:
# Labels for training images
print training_data_labels

[5 0 4 ..., 8 4 8]


In [13]:
classifier = svm.LinearSVC()
classifier.fit(training_data , training_data_labels)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [17]:
# Lets try our model on Test data.
predicted_labels = classifier.predict(test_data)
print np.

<type 'numpy.ndarray'>


In [33]:
# Classification report
print "Classification report for classifier %s:\n%s" % (
        classifier, 
        metrics.classification_report(test_data_labels, predicted_labels))

Classification report for classifier LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0):
             precision    recall  f1-score   support

          0       0.95      0.98      0.96       980
          1       0.96      0.98      0.97      1135
          2       0.93      0.88      0.91      1032
          3       0.89      0.91      0.90      1010
          4       0.92      0.93      0.92       982
          5       0.88      0.85      0.87       892
          6       0.93      0.95      0.94       958
          7       0.92      0.92      0.92      1028
          8       0.87      0.86      0.86       974
          9       0.90      0.89      0.89      1009

avg / total       0.92      0.92      0.91     10000



In [35]:
# confusion matrix
print("Confusion matrix:\n%s" % metrics.confusion_matrix(
                                    test_data_labels, 
                                    predicted_labels))

Confusion matrix:
[[ 959    0    2    1    0    6    8    2    2    0]
 [   0 1113    4    1    0    1    4    1   11    0]
 [  10    9  910   23   11    4   12   10   40    3]
 [   5    2   19  915    3   20    5   12   20    9]
 [   1    3    5    3  914    0   10    3    6   37]
 [  10    3    1   38   11  761   20    8   31    9]
 [   9    4    7    2    6   20  907    1    2    0]
 [   2    9   21    6    6    1    1  945    4   33]
 [   8   13    8   23   13   38    8   15  835   13]
 [   6    8    2   15   34   10    0   27   13  894]]


In [44]:
#Lets check the model's accuracy on the test data.
n_correct_predictions = sum([int(x==y) for x,y in zip(
                            test_data_labels, predicted_labels)])
print "Test data Result: %s / %s, Percentage: %f" % (
            n_correct_predictions,
            len(test_data),
            np.float(n_correct_predictions)/len(test_data))

Test data Result: 9153 / 10000, Percentage: 0.915300
